//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYC311Dashboard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NYC311Dashboard.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unspecified.
        /// </summary>
        public static string borough_unspecified {
            get {
                return ResourceManager.GetString("borough_unspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total count.
        /// </summary>
        public static string chart_name_total_count {
            get {
                return ResourceManager.GetString("chart_name_total_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total duration.
        /// </summary>
        public static string chart_name_total_duration {
            get {
                return ResourceManager.GetString("chart_name_total_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available.
        /// </summary>
        public static string data_none_available {
            get {
                return ResourceManager.GetString("data_none_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} selected!.
        /// </summary>
        public static string empty_selction {
            get {
                return ResourceManager.GetString("empty_selction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No boroughs selected!.
        /// </summary>
        public static string empty_selction_boroughs {
            get {
                return ResourceManager.GetString("empty_selction_boroughs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get chart options..
        /// </summary>
        public static string failed_chart_options {
            get {
                return ResourceManager.GetString("failed_chart_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get data..
        /// </summary>
        public static string failed_to_get_data {
            get {
                return ResourceManager.GetString("failed_to_get_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to render chart. Please check your connection and try again..
        /// </summary>
        public static string failed_to_render_chart {
            get {
                return ResourceManager.GetString("failed_to_render_chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boroughs.
        /// </summary>
        public static string groupy_category_boroughs {
            get {
                return ResourceManager.GetString("groupy_category_boroughs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select options.
        /// </summary>
        public static string label_select_options {
            get {
                return ResourceManager.GetString("label_select_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading, please wait....
        /// </summary>
        public static string loading_service_default_loading {
            get {
                return ResourceManager.GetString("loading_service_default_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m loading here!.
        /// </summary>
        public static string loading_service_loading_here {
            get {
                return ResourceManager.GetString("loading_service_loading_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get data..
        /// </summary>
        public static string messaging_service_default_error {
            get {
                return ResourceManager.GetString("messaging_service_default_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No requests loaded..
        /// </summary>
        public static string messaging_service_default_info {
            get {
                return ResourceManager.GetString("messaging_service_default_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No requests loaded..
        /// </summary>
        public static string messaging_service_default_message {
            get {
                return ResourceManager.GetString("messaging_service_default_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Please try again!.
        /// </summary>
        public static string messaging_service_error_occurred {
            get {
                return ResourceManager.GetString("messaging_service_error_occurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh all data for NYC 311 requests?.
        /// </summary>
        public static string messaging_service_refresh_requests {
            get {
                return ResourceManager.GetString("messaging_service_refresh_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string messaging_service_title_confirm {
            get {
                return ResourceManager.GetString("messaging_service_title_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string messaging_service_title_error {
            get {
                return ResourceManager.GetString("messaging_service_title_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please refresh data to populate boroughs list!.
        /// </summary>
        public static string refresh_data_boroughs_list {
            get {
                return ResourceManager.GetString("refresh_data_boroughs_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to closed.
        /// </summary>
        public static string request_status_closed {
            get {
                return ResourceManager.GetString("request_status_closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one or more boroughs to see zip code data..
        /// </summary>
        public static string select_boroughs_zip_code_data {
            get {
                return ResourceManager.GetString("select_boroughs_zip_code_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Zip Codes.
        /// </summary>
        public static string select_zip_codes {
            get {
                return ResourceManager.GetString("select_zip_codes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borough.
        /// </summary>
        public static string title_borough {
            get {
                return ResourceManager.GetString("title_borough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests by.
        /// </summary>
        public static string title_requests {
            get {
                return ResourceManager.GetString("title_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        public static string title_zip_code {
            get {
                return ResourceManager.GetString("title_zip_code", resourceCulture);
            }
        }
    }
}
